// Metadata untuk grid downloader di halaman utama.
// - "mono"   : singkatan yang ditampilkan kalau logo asli gagal dimuat (fallback)
// - "accent" : warna cincin/border dekoratif di sekitar kotak logo
// - "logo"   : path lokal ke file logo di folder public/assets/
export const PLATFORMS = [
  {
    id: "tiktok",
    name: "TikTok",
    mono: "TT",
    accent: "#25F4EE",
    logo: "/assets/tiktok.png",
    hint: "Video atau slide foto TikTok, tanpa watermark.",
    placeholder: "https://vt.tiktok.com/....",
  },
  {
    id: "instagram",
    name: "Instagram",
    mono: "IG",
    accent: "#E1306C",
    logo: "/assets/instagram.jpg",
    hint: "Reels, video, atau carousel foto.",
    placeholder: "https://www.instagram.com/reel/....",
  },
  {
    id: "facebook",
    name: "Facebook",
    mono: "FB",
    accent: "#1877F2",
    logo: "/assets/facebook.png",
    hint: "Video atau foto dari post/reel Facebook.",
    placeholder: "https://www.facebook.com/share/....",
  },
  {
    id: "pinterest",
    name: "Pinterest",
    mono: "PT",
    accent: "#E60023",
    logo: "/assets/pinterest.jpg",
    hint: "Pin gambar maupun video.",
    placeholder: "https://pin.it/....",
  },
  {
    id: "twitter",
    name: "X / Twitter",
    mono: "X",
    accent: "#E7E9EA",
    logo: "/assets/x.jpg",
    hint: "Foto atau video dari sebuah postingan.",
    placeholder: "https://x.com/user/status/....",
  },
  {
    id: "douyin",
    name: "Douyin",
    mono: "DY",
    accent: "#FE2C55",
    logo: "/assets/douyin.png",
    hint: "Video atau slide foto Douyin, tanpa watermark.",
    placeholder: "https://v.douyin.com/....",
  },
  {
    id: "youtube",
    name: "YouTube",
    mono: "YT",
    accent: "#FF0000",
    logo: "/assets/youtube.png",
    hint: "Unduh sebagai video MP4 atau audio MP3.",
    placeholder: "https://www.youtube.com/watch?v=....",
    hasFormat: true,
  },
  {
    id: "threads",
    name: "Threads",
    mono: "TH",
    accent: "#E4E4E4",
    logo: "/assets/threads.png",
    hint: "Foto atau video dari sebuah postingan Threads.",
    placeholder: "https://www.threads.net/@user/post/....",
  },
  {
    id: "bilibili",
    name: "Bilibili",
    mono: "BB",
    accent: "#FB7299",
    logo: "/assets/bilibili.png",
    hint: "Video dari Bilibili (mainland) maupun Bilibili.tv (internasional).",
    placeholder: "https://www.bilibili.com/video/BV....",
  },
  {
    id: "spotify",
    name: "Spotify",
    mono: "SP",
    accent: "#1DB954",
    logo: "/assets/spotify.png",
    hint: "Unduh lagu dari link track Spotify.",
    placeholder: "https://open.spotify.com/track/....",
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    mono: "SC",
    accent: "#FF7A33",
    logo: "/assets/soundcloud.jpg",
    hint: "Unduh audio dari link track SoundCloud.",
    placeholder: "https://soundcloud.com/artis/judul",
  },
  {
    id: "applemusic",
    name: "Apple Music",
    mono: "AM",
    accent: "#FA57C1",
    logo: "/assets/applemusic.png",
    hint: "Unduh lagu dari link Apple Music.",
    placeholder: "https://music.apple.com/id/album/....",
  },
  {
    id: "reddit",
    name: "Reddit",
    mono: "RD",
    accent: "#FF4500",
    logo: "/assets/reddit.png",
    hint: "Video dari postingan Reddit, lengkap dengan audio.",
    placeholder: "https://www.reddit.com/r/.../comments/....",
  },
  {
    id: "pixiv",
    name: "Pixiv",
    mono: "PX",
    accent: "#0096FA",
    logo: "/assets/pixiv.png",
    hint: "Gambar (semua halaman) atau animasi dari karya Pixiv.",
    placeholder: "https://www.pixiv.net/artworks/....",
  },
  {
    id: "rednote",
    name: "RedNote",
    mono: "RN",
    accent: "#FF2442",
    logo: "/assets/rednote.png",
    hint: "Video atau foto dari postingan RedNote (Xiaohongshu).",
    placeholder: "https://xhslink.com/....",
  },
  {
    id: "terabox",
    name: "TeraBox",
    mono: "TB",
    accent: "#0061D5",
    logo: "/assets/terabox.png",
    hint: "Unduh file dari link share TeraBox.",
    placeholder: "https://terabox.com/s/....",
  },
  {
    id: "bandcamp",
    name: "Bandcamp",
    mono: "BC",
    accent: "#1DA0C3",
    logo: "/assets/bandcamp.png",
    hint: "Unduh lagu atau album Bandcamp sebagai MP3.",
    placeholder: "https://artis.bandcamp.com/track/....",
  },
];

export function getPlatform(id) {
  return PLATFORMS.find((p) => p.id === id);
}
